import React from "react";
import Image from 'next/image';

export const metadata = {
  title: 'Tech Stacks | Portfolio',
  description: 'Generated by create next app',
  openGraph: {
    title: 'Tech Stacks | Portfolio',
    description: 'The React Framework for the Web',
    url: 'http://localhost:3000/tech-stacks',
    siteName: 'Portfolio',
    images: [
      {
        url: 'http://localhost:3000/teck-stacks/teckstacks-og.png',
        width: 800,
        height: 600,
      },
      {
        url: 'http://localhost:3000/teck-stacks/teckstacks-og-alt.png',
        width: 1800,
        height: 1600,
        alt: 'My custom alt',
      },
    ],
    locale: 'en_US',
    type: 'website',
  },
}


const Techstacks = () => {
    
    return (
        <main>
            <section class="techstack_section">

                <div class="techstack_container">
                    <h1 class="title">Tech Stacks</h1>
                    <ul>
                        <li>
                            <Image src="assets/images/html.png" width="100%" height="100%" layout="responsive" objectFit="cover" alt="" />
                            <h5>HTML</h5>
                        </li>
                        <li>
                            <Image src="assets/images/css.png" width="100%" height="100%" layout="responsive" objectFit="cover" alt="" />
                            <h5>CSS</h5>
                        </li>
                        <li>
                            <Image src="assets/images/scss.png" width="100%" height="100%" layout="responsive" objectFit="cover" alt="" />
                            <h5>SCSS</h5>
                        </li>
                        <li>
                            <Image src="assets/images/jquery.png" width="100%" height="100%" layout="responsive" objectFit="cover" alt="" />
                            <h5>JQuery</h5>
                        </li>
                        <li>
                            <Image src="assets/images/javascript.svg" width="100%" height="100%" layout="responsive" objectFit="cover" alt="" />
                            <h5>Javascript</h5>
                        </li>
                        <li>
                            <Image src="assets/images/react.png" width="100%" height="100%" layout="responsive" objectFit="cover" alt="" />
                            <h5>React Js</h5>
                        </li>
                        <li>
                            <Image src="assets/images/nextjs.png" width="100%" height="100%" layout="responsive" objectFit="cover" alt="" />
                            <h5>Next Js</h5>
                        </li>
                        <li>
                            <Image src="assets/images/laravel.png" width="100%" height="100%" layout="responsive" objectFit="cover" alt="" />
                            <h5>Laravel</h5>
                        </li>
                        <li>
                            <Image src="assets/images/mysql.png" width="100%" height="100%" layout="responsive" objectFit="cover" alt="" />
                            <h5>MySql</h5>
                        </li>
                        <li>
                            <Image src="assets/images/bootstrap.png" width="100%" height="100%" layout="responsive" objectFit="cover" alt="" />
                            <h5>Boostrap</h5>
                        </li>
                        <li>
                            <Image src="assets/images/chakra-ui.png" width="100%" height="100%" layout="responsive" objectFit="cover" alt="" />
                                <h5>Chakra UI</h5>
                        </li>
                        <li>
                            <Image src="assets/images/tailwind.png" width="100%" height="100%" layout="responsive" objectFit="cover" alt="" />
                            <h5>Tailwind CSS</h5>
                        </li>
                        <li>
                            <Image src="assets/images/github.png" width="100%" height="100%" layout="responsive" objectFit="cover" alt="" />
                            <h5>Github</h5>
                        </li>
                        <li>
                            <Image src="assets/images/figma.png" width="100%" height="100%" layout="responsive" objectFit="cover" alt="" />
                            <h5>Figma</h5>
                        </li>
                        <li>
                            <Image src="assets/images/bitbucket.png" width="100%" height="100%" layout="responsive" objectFit="cover" alt="" />
                            <h5>Bitbucket</h5>
                        </li>
                        <li>
                            <Image src="assets/images/vscode.png" width="100%" height="100%" layout="responsive" objectFit="cover" alt="" />
                            <h5>VS Code</h5>
                        </li>
                        <li>
                            <Image src="assets/images/greensock.webp" width="100%" height="100%" layout="responsive" objectFit="cover" alt="" />
                            <h5>GSAP</h5>
                        </li>
                        <li>
                            <Image src="assets/images/seo.svg" width="100%" height="100%" layout="responsive" objectFit="cover" alt="" />
                            <h5>SEO</h5>
                        </li>
                    </ul>
                </div>  
            </section>
        </main>
    );

}

export default Techstacks;